AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A serverless component for conversion from MOV to MP4 
Parameters:
  ConversionTimeout:
    Type: Number
    Default: 180
  InputS3BucketName:
    Type: String
    Default: 'ffmpeg-lambda-convert-input'
    MinLength: 3
  OutputS3BucketName:
    Type: String
    Default: 'ffmpeg-lambda-convert-output'
    MinLength: 3
Resources:
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputS3BucketName
  ConvertFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Timeout: !Ref ConversionTimeout
      MemorySize: 1024
      Runtime: nodejs8.10
      CodeUri: src/
      Layers:
        - 'arn:aws:lambda:us-west-2:255827576516:layer:ffmpeg:1'
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref OutputS3BucketName
      - S3ReadPolicy:
          BucketName: !Ref InputS3BucketName
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputS3Bucket
          EXTENSION: '.mp4'
          MIME_TYPE: 'video/mp4'
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputS3Bucket
            Events: s3:ObjectCreated:*
  OutputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputS3BucketName

Outputs:
  InputS3Bucket:
    Description: Input S3 bucket
    Value: !Ref InputS3Bucket
  OutputS3Bucket:
    Description: Output S3 bucket
    Value: !Ref OutputS3Bucket

